version: "2"
services:
  installation-ui:
    container_name: installation-ui
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    ports:
      - 3333:3333
    networks:
      - installation_app

networks:
  installation_app: